export const events = [
  { id: 1, "eventTitle": "Festival 1", "eventDate": "2023-01-31", "eventSalesDate": "2023-01-30", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription":"Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi."},
  { id: 2, "eventTitle": "Festival 2", "eventDate": "2023-01-31", "eventSalesDate": "2023-01-30", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 3, "eventTitle": "Festival 3", "eventDate": "2023-01-25", "eventSalesDate": "2023-01-03", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 4, "eventTitle": "Concert 1", "eventDate": "2023-03-30", "eventSalesDate": "2023-03-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 5, "eventTitle": "Concert 2", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 6, "eventTitle": "Concert 3", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 7, "eventTitle": "Concert 4", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 8, "eventTitle": "Concert 5", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 9, "eventTitle": "Festival 4", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 10, "eventTitle": "Festival 5", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 11, "eventTitle": "Festival 6", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." },
  { id: 12, "eventTitle": "Concert 6", "eventDate": "2023-02-20", "eventSalesDate": "2023-01-25", "eventOrganizer": "John", "eventTicketLimit": 4, "eventDescription": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dicta tenetur cum saepe? Quaerat, maxime beatae nihil sit quod explicabo corporis ea ex rem ut aliquid voluptates architecto repellendus omnis commodi." }
]

export const accounts = [
  { id: 1, "username":"John", "password":"123456", "email":"john.johnsson@john.com"},
  { id: 2, "username":"Test", "password":"testsson", "email":"test@testsson.com"},
]